# Generated by Django 5.0.6 on 2024-05-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_product_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_desc',
            new_name='desc',
        ),
    ]
